config/routes.rb
Spotifystats::Application.routes.draw do
  
  resources :tracks
  
  root "stats#show"

  resource :stat do 
    member do
      get :tracks_by_day
    end
  end

  

end

app/models/track.rb
class Track < ActiveRecord::Base

  # Feed is updated daily, don't add duplicates for a single day
  # This will make sure the date, track and artist are unique
  # (A song won't show up twice in one day)
  validates_uniqueness_of :date, :scope => [:track_name, :artist_name]
  validates :date, :track_name, :artist_name, :album_name, :num_streams, presence: true

  def self.save_data_from_spotify_chart_api
    response = HTTParty.get('http://charts.spotify.com/api/tracks/most_streamed/global/daily/latest')
      track_data = JSON.parse(response.body)["tracks"]
	  tracks = track_data.map do |line|
	    t = Track.new
	    t.date = line['date']
	    t.country = line['country']
	    t.track_url = line['track_url']
	    t.track_name = line['track_name']
	    t.artist_name = line['artist_name']
	    t.artist_url = line['artist_url']
	    t.album_name = line['album_name']
	    t.album_url = line['album_url']
	    t.artwork_url = line['artwork_url']
	    t.num_streams = line['num_streams']
	    t.window_type = line['window_type']
	    t.save
	    t
	  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def tracks_by_day
    render json: Track.group(:track_name).group_by_day(:date, format: "%Y-%m-%d").maximum(:num_streams).chart_json
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
  	@tracks = Track.all
  end

  def show
  	@track = Track.find(params[:id])
  end

  def new
    @track = Track.new
  end

  def create
  	@track = Track.new(track_params)

  	if @track.save
  	  redirect_to @tracks
  	else
  	  render 'new'
  	end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
  	@track = Track.find(params[:id])

  	if @track.update(track_params)
  	  redirect_to @track
  	else
  	  render 'edit'
  	end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
 
    redirect_to tracks_path
  end  

  private
  def track_params
    params.require(:track).permit(:date, :track_name, :artist_name, :album, :num_streams)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotifystats</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/stats/show.html.erb
<p><%= link_to 'Raw View of Tracks', controller: 'tracks' %></p>
<p><%= link_to 'Create Test Track', new_track_path %></p>


<div class="col-xs-12">
  <h3>Top Tracks By Day</h3>
  <%= line_chart tracks_by_day_stat_path %>
</div>

app/views/tracks/_form.html.erb
<%= form_for @track do |f| %>
  
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h3><font color=red><%= pluralize(@track.errors.count, "error") %> 
           kept this track from being saved:</font></h3>
      <ul>
        <% @track.errors.full_messages.each do |msg| %>
          <font color=red><li><%= msg %></li></font>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :track_name %><br>
    <%= f.text_field :track_name %>
  </p>

  <p>
    <%= f.label :artist_name %><br>
    <%= f.text_field :artist_name %>
  </p>

  <p>
    <%= f.label :album_name %><br>
    <%= f.text_field :album_name %>
  </p>

  <p>
    <%= f.label 'Number of Streams' %><br>
    <%= f.text_field :num_streams %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>
<h2><font color=red>This is for testing purposes only!!</font></h2>

<% render 'form' %>

<%= link_to 'Back', stat_path %>

app/views/tracks/index.html.erb
<h1>Listing Tracks</h1>
 
<table>
  <tr>
    <th>Date</th>
    <th>Track</th>
    <th>Artist</th>
    <th>Album</th>
    <th>Number of Streams</th>
  </tr>
 
  <% @tracks.each do |track| %>
    <tr>
      <td><%= track.date %></td>
      <td><%= track.track_name %></td>
      <td><%= track.artist_name %></td>
      <td><%= track.album_name %></td>
      <td><%= track.num_streams %></td>
      <td><%= link_to 'Show Track', track_path(track) %></td>
      <td><%= link_to 'Edit Track', edit_track_path(track) %></td>
      <td><%= link_to 'Destroy', track_path(track),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/tracks/new.html.erb
<h1>New Track</h1>
<h2><font color=red>This is for testing purposes only!!</font></h2>

<%= render 'form' %>

<%= link_to 'Back', stat_path %>

app/views/tracks/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @track.date %>
</p>
 
<p>
  <strong>Track Name:</strong>
  <%= @track.track_name %>
</p>

<p>
  <strong>Artist Name:</strong>
  <%= @track.artist_name %>
</p>

<p>
  <strong>Album Name:</strong>
  <%= @track.album_name %>
</p>

<p>
  <strong>Number of Streams:</strong>
  <%= @track.num_streams %>
</p>

<%= link_to 'Back', tracks_path %>
| <%= link_to 'Edit', edit_track_path(@track) %>